package main

import (
	"github.com/gofiber/fiber/v2"
	"log"
	"triplink/backend/database"
	"triplink/backend/routes"

	_ "triplink/backend/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Triplink API
// @version 1.0
func main() {
	database.Connect()

	app := fiber.New()

	routes.Setup(app)

	log.Fatal(app.Listen(":3000"))
}
