package main

import (
	"log"
	"triplink/backend/database"
	"triplink/backend/routes"
	"triplink/backend/services"

	"github.com/gofiber/fiber/v2"

	_ "triplink/backend/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Triplink API
// @version 1.0
func main() {
	// Connect to database
	database.Connect()

	// Initialize notification service
	initNotificationService()

	// Register notification triggers
	services.RegisterNotificationTriggers()

	// Create Fiber app
	app := fiber.New()

	// Setup routes
	routes.Setup(app)

	// Start server
	log.Fatal(app.Listen(":8080"))
}
